config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :subcategories
  resources :categories
  resources :items do
    get :autocomplete_sublocation_name, on: :collection
    get :autocomplete_subcategory_name, on: :collection
  end
  resources :locations
  resources :sublocations

  root to: "items#index"

end

app/models/sublocation.rb
class Sublocation < ActiveRecord::Base
  belongs_to :location
  has_many :items
  validates :name, presence: true
  validates :location, presence: true
  def loc_name
    location.name
  end
  def with_loc_name
    "#{loc_name} - #{self.name}"
  end
end

app/controllers/sublocations_controller.rb
class SublocationsController < ApplicationController
  before_action :set_sublocation, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  # GET /sublocations
  # GET /sublocations.json
  def index
    @sublocations_grid = initialize_grid(Sublocation)
  end

  # GET /sublocations/1
  # GET /sublocations/1.json
  def show
    @items_grid = initialize_grid(
    Item.where("sublocation_id" => @sublocation.id),
    joins: :sublocation,
    joins: :subcategory
    )
  end

  # GET /sublocations/new
  def new
    @sublocation = Sublocation.new
  end

  # GET /sublocations/1/edit
  def edit
  end

  # POST /sublocations
  # POST /sublocations.json
  def create
    @sublocation = Sublocation.new(sublocation_params)

    respond_to do |format|
      if @sublocation.save
        format.html { redirect_to @sublocation, notice: 'Sublocation was successfully created.' }
        format.json { render :show, status: :created, location: @sublocation }
      else
        format.html { render :new }
        format.json { render json: @sublocation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sublocations/1
  # PATCH/PUT /sublocations/1.json
  def update
    respond_to do |format|
      if @sublocation.update(sublocation_params)
        format.html { redirect_to @sublocation, notice: 'Sublocation was successfully updated.' }
        format.json { render :show, status: :ok, location: @sublocation }
      else
        format.html { render :edit }
        format.json { render json: @sublocation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sublocations/1
  # DELETE /sublocations/1.json
  def destroy
    @sublocation.destroy
    respond_to do |format|
      format.html { redirect_to sublocations_url, notice: 'Sublocation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sublocation
      @sublocation = Sublocation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sublocation_params
      params.require(:sublocation).permit(:name, :location_id)
    end
end

app/helpers/sublocations_helper.rb
module SublocationsHelper
end

app/views/sublocations/_form.html.erb
<%= form_for @sublocation, :html => { :class => "form-horizontal sublocation" } do |f| %>

    <% if @sublocation.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@sublocation.errors.count, "error") %> prohibited this sublocation from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @sublocation.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@sublocation[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :location_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.collection_select :location_id, Location.all, :id, :name, :class => 'form-control' %>
    </div>
    <%= error_span(@sublocation[:location_id]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            sublocations_path, :class => 'btn btn-default' %>

<% end %>

app/views/sublocations/edit.html.erb
<%- model_class = Sublocation -%>
<div class="page-header">
  <h3><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h3>
</div>
<%= render :partial => 'form' %>

app/views/sublocations/index.html.erb
<%- model_class = Sublocation -%>
<div class="page-header">
  <h3><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h3>
</div>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_sublocation_path,
            :class => 'btn btn-primary btn-margin-bottom' %>

<%= grid(@sublocations_grid) do |g|
  g.column name: 'Name', attribute: 'name' do |subloc|
    link_to subloc.name, sublocation_path(subloc)
  end

  g.column name: 'Location', attribute: 'name', assoc: :location do |subloc|
    link_to subloc.location.name, location_path(subloc.location)
  end

  g.column name: 'Actions' do |subloc|
    buffer = link_to t('.edit', :default => t("helpers.links.edit")),
                edit_sublocation_path(subloc), :class => 'btn btn-default btn-xs'
    buffer += link_to t('.destroy', :default => t("helpers.links.destroy")),
      sublocation_path(subloc),
      :method => :delete,
      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
      :class => 'btn btn-xs btn-danger btn-margin-left'
      raw buffer
  end
end %>

app/views/sublocations/new.html.erb
<%- model_class = Sublocation -%>
<div class="page-header">
  <h3><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h3>
</div>
<%= render :partial => 'form' %>

app/views/sublocations/show.html.erb
<%- model_class = Sublocation -%>
<div class="page-header">
  <h3><%=t '.title', :default => model_class.model_name.human.titleize %></h3>
</div>
<div class="col-md-12">
  <div class="col-md-4">
<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @sublocation.name %></dd>
  <dt><strong>Location:</strong></dt>
  <dd><%= link_to @sublocation.loc_name, location_path(@sublocation.location) %></dd>
</dl>
</div>
<div class="col-md-4"></div>
<div class="col-md-4">
<%= link_to t('.back', :default => t("helpers.links.back")),
              sublocations_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_sublocation_path(@sublocation), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              sublocation_path(@sublocation),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>
</div>
<div class="col-md-12">

              <strong>Items:</strong>
              <% @items = @sublocation.items %>
              <%= render partial: 'items/list'%>
            </div>