config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :subcategories
  resources :categories
  resources :items do
    get :autocomplete_sublocation_name, on: :collection
    get :autocomplete_subcategory_name, on: :collection
  end
  resources :locations
  resources :sublocations

  root to: "items#index"

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :sublocation
  belongs_to :subcategory
  has_one :category, through: :subcategory
  has_one :location, through: :sublocation
  has_many :assets, dependent: :destroy
  validates :name, presence: true
  validates :sublocation, presence: true
  validates :subcategory, presence: true
  accepts_nested_attributes_for :assets,
    allow_destroy: true,
    reject_if: :all_blank
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  autocomplete :sublocation, :name, :full => true, :display_value => :with_loc_name, :extra_data => [:location_id]
  autocomplete :subcategory, :name, :full => true, :display_value => :with_cat_name, :extra_data => [:category_id]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
    @items_grid = initialize_grid(Item,
    joins: :sublocation,
    joins: :subcategory
    )
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
    3.times { @item.assets.build }
  end

  # GET /items/1/edit
  def edit
    3.times { @item.assets.build }
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)
    if @item.stock.nil?
      @item.stock = 0
    end
    if @item.price.nil?
      @item.price = 0
    end
    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    # params[:item][:existing_asset_attributes] ||= {}
    if @item.stock.nil?
      @item.stock = 0
    end
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :description, :sublocation_id, :subcategory_id, :stock, :price, assets_attributes: [ :_destroy, :name, :id, :file ])
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for @item, :html => { :class => "form-horizontal item", multipart: true } do |f| %>

    <% if @item.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @item.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@item[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%= error_span(@item[:description]) %>
  </div>
  <div class="control-group">
    <%= f.label :sublocation_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.autocomplete_field :sublocation ,autocomplete_sublocation_name_items_path, 'data-auto-focus' => true, 'data-showNoMatches' => false, id_element: '.subloc', class: "form-control" %>
      <%= f.text_field :sublocation_id, :class => 'hidden subloc' %>
    </div>
    <%= error_span(@item[:sublocation_id]) %>
  </div>
  <div class="control-group">
    <%= f.label :subcategory_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.autocomplete_field :subcategory, autocomplete_subcategory_name_items_path, 'data-auto-focus' => true, id_element: '.subcat', class: "form-control" %>
      <%= f.text_field :subcategory_id, :class => 'hidden subcat' %>
    </div>
    <%= error_span(@item[:subcategory_id]) %>
  </div>
  <div class="control-group">
    <%= f.label :price, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :price, :class => 'form-control' %>
    </div>
    <%= error_span(@item[:price]) %>
  </div>
  <div class="control-group">
    <%= f.label :stock, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :stock, :class => 'form-control' %>
    </div>
    <%= error_span(@item[:stock]) %>
  </div>
  <h3>Assets</h3>
  <%= f.fields_for :assets do |a| %>
  <div class="col-md-8" >
    <div class="col-md-3">
      <%= a.text_field :name, placeholder: "Name" %>
    </div>
    <div class="col-md-3">
      <%= a.file_field :file %>
    </div>
    <div class="col-md-2">
      <% if a.object.persisted? %>
      <%= a.check_box :_destroy %>
      <%= a.label :_destroy, "Destroy" %>
      <% end %>
    </div>
  </div>
  <% end %>


  <div class="col-md-8" >
    <br />
    <br />
  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            items_path, :class => 'btn btn-default' %>
  </div>
<% end %>

app/views/items/_list.html.erb
<% if @items_grid.empty? %>
  <div class="col-md-12">
  <strong>There are no items here!</strong>
  </div>
<% else %>
<%= grid(@items_grid) do |g|
  g.column name: 'Name', attribute: 'name' do |item|
    link_to item.name, item_path(item)
  end
  g.column name: 'Description', attribute: 'description'  do |item|
    link_to item.description, item_path(item)
  end
  g.column name: 'Location', attribute: 'name', assoc: :sublocation do |item|
    link_to item.sublocation.with_loc_name, sublocation_path(item.sublocation)
  end
  g.column name: 'Category', attribute: 'name' , assoc: :subcategory do |item|
    link_to item.subcategory.with_cat_name, subcategory_path(item.subcategory)
  end
  g.column name: 'Stock', attribute: 'stock' do |item|
    item.stock
  end

  g.column name: 'Price', attribute: 'price', filter: false do |item|
    item.price
  end
  g.column name: 'Actions' do |item|
    buffer = link_to t('.edit', :default => t("helpers.links.edit")),
                edit_item_path(item), :class => 'btn btn-default btn-xs'

    buffer += link_to t('.destroy', :default => t("helpers.links.destroy")),
      item_path(item),
      :method => :delete,
      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
      :class => 'btn btn-xs btn-danger btn-margin-left'
    raw buffer
  end
end -%>
<% end %>

app/views/items/edit.html.erb
<%- model_class = Item -%>
<div class="page-header">
  <h3><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h3>
</div>
<%= render :partial => 'form' %>

app/views/items/index.html.erb
<%- model_class = Item -%>
<div class="page-header">
  <h3><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h3>
</div>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_item_path,
            :class => 'btn btn-primary btn-margin-bottom' %>

<%= render partial: 'list' %>

app/views/items/new.html.erb
<%- model_class = Item -%>
<div class="page-header">
  <h3><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h3>
</div>
<%= render :partial => 'form' %>

app/views/items/show.html.erb
<%- model_class = Item -%>
<div class="page-header">
  <h3><%=t '.title', :default => model_class.model_name.human.titleize %></h3>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @item.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @item.description %></dd>
  <dt><strong>Location:</strong></dt>
  <dd><%= @item.sublocation.with_loc_name %></dd>
  <dt><strong>Category:</strong></dt>
  <dd><%= @item.subcategory.with_cat_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @item.price %></dd>
  <dt><strong><%= model_class.human_attribute_name(:stock) %>:</strong></dt>
  <dd><%= @item.stock %></dd>
  <dt><strong>Assets:</strong></dt>
  <% for asset in @item.assets %>
  <dd><%= link_to asset.name, asset.file.url, target: "_blank" %></dd>
<% end %>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              items_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_item_path(@item), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              item_path(@item),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>