config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :subcategories
  resources :categories
  resources :items do
    get :autocomplete_sublocation_name, on: :collection
    get :autocomplete_subcategory_name, on: :collection
  end
  resources :locations
  resources :sublocations

  root to: "items#index"

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :subcategories
  has_many :items, through: :subcategories
  validates :name, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /categories
  # GET /categories.json
  def index
    @categories_grid = initialize_grid(Category)
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @items_grid = initialize_grid(
    Item.joins(:subcategory).where("subcategories.category_id" => @category.id),
    joins: :sublocation
    )
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for @category, :html => { :class => "form-horizontal category" } do |f| %>

    <% if @category.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @category.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@category[:name]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            categories_path, :class => 'btn btn-default' %>

<% end %>

app/views/categories/edit.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h3><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h3>
</div>
<%= render :partial => 'form' %>

app/views/categories/index.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h3><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h3>
</div>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_category_path,
            :class => 'btn btn-primary btn-margin-bottom' %>

<%= grid(@categories_grid) do |g|
  g.column name: 'Name', attribute: 'name' do |cat|
    link_to cat.name, category_path(cat)
  end

  g.column name: 'Actions' do |cat|
    buffer = link_to t('.edit', :default => t("helpers.links.edit")),
                edit_category_path(cat), :class => 'btn btn-default btn-xs'

    buffer += link_to t('.destroy', :default => t("helpers.links.destroy")),
      category_path(cat),
      :method => :delete,
      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
      :class => 'btn btn-xs btn-danger btn-margin-left'
    raw buffer

  end
end
%>

app/views/categories/new.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h3><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h3>
</div>
<%= render :partial => 'form' %>

app/views/categories/show.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h3><%=t '.title', :default => model_class.model_name.human.titleize %></h3>
</div>
<div class="col-md-12">
<div class="col-md-4">
<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @category.name %></dd>
</dl>

<dl class="dl-horizontal">
  <dt><strong>Subcategories:</strong></dt>
  <dd>
    <ul class="sub-list">
      <% @category.subcategories.each do |subcat| %>
        <li><%= link_to subcat.name, subcategory_path(subcat) %></li>
      <% end %>
    </ul>
  </dd>
</dl>
</div>
<div class="col-md-4"></div>
<div class="col-md-4">
<%= link_to t('.back', :default => t("helpers.links.back")),
              categories_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_category_path(@category), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              category_path(@category),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>
</div>
<div class="col-md-12">
  <strong>Items:</strong>
  <%= render partial: 'items/list'%>
</div>