config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :subcategories
  resources :categories
  resources :items do
    get :autocomplete_sublocation_name, on: :collection
    get :autocomplete_subcategory_name, on: :collection
  end
  resources :locations
  resources :sublocations

  root to: "items#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Inven</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <%= nav_bar fixed: :top, brand: 'Inventory Manager', responsive: true do  %>
    <%= menu_group do %>
      <%= menu_item "Home", root_path %>
      <%= menu_item "Items", items_path %>
      <%= drop_down "Categories" do %>
        <%= menu_item "Categories", categories_path %>
        <%= menu_item "+New Category", new_category_path %>
        <%= menu_item "Subcategories", subcategories_path %>
        <%= menu_item "+New Subcategory", new_subcategory_path %>
      <% end %>
      <%= drop_down "Locations" do %>
        <%= menu_item "Locations", locations_path %>
        <%= menu_item "+New Location", new_location_path %>
        <%= menu_item "Sublocations", sublocations_path %>
        <%= menu_item "+New Sublocation", new_sublocation_path %>
      <% end %>
      <%= menu_item "+New Item", new_item_path %>
    <% end %>
    <%= menu_group pull: :right do %>
      <% if current_user %>
        <%= menu_item "Log Out", destroy_user_session_path, method: :delete, class: "navbar-right" %>
      <% end %>
    <% end %>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger" style="margin-top: 65px;"><%= alert %></p>
  <% end %>
  <% if notice %>
    <p class="alert alert-info" style="margin-top: 65px;"><%= notice %></p>
  <% end %>
<%= yield %>

</div>

</body>
</html>